import Head from 'next/head';
import Image from 'next/image';
import React from 'react';
import { Line, Bar } from 'react-chartjs-2';
import DotsElement from '@/components/DotsElement';
import { barData, barOptions, lineData, lineOptions } from '@/utils/chartInput';
import Link from 'next/link';

import {
  Container,
  OtlinedButton,
  AppBar,
  LinkList,
  ChartHeader,
  ChartDescription,
  Chart,
  ChartTop,
  Chips,
  Calls,
  ChartWrapper,
} from '../components/sharedstyles';

export default function Home() {
  return (
    <>
      <Head>
        <title>Аналитика</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <AppBar>
          <Link href="/">
            <Image
              src="/logo.svg"
              alt="Vercel Logo"
              width={195}
              height={34}
              priority
            />
          </Link>
          <LinkList>
            <li>О нас</li>
            <li>
              <Link href="/charts">Платформа</Link>
            </li>
            <li>Портфолио</li>
            <li>Контакты</li>
          </LinkList>
          <Link href="/login">
            <OtlinedButton>Вход</OtlinedButton>
          </Link>
        </AppBar>
        <ChartHeader>
          <h1>
            Вся аналитика
            <br /> в одном кабинете
          </h1>
          <p>
            Отслеживайте работу голосового ассистента
            <br /> в личном кабинете
          </p>
        </ChartHeader>
        <ChartDescription>
          <p>
            Уникальные виджеты позволяют настроить дашборд под задачи различных
            подразделений вашей компании
          </p>
        </ChartDescription>
        <ChartWrapper>
          <Chart>
            <ChartTop>
              <h4 style={{ fontSize: 18 }}>Звонки</h4>
              <DotsElement />
            </ChartTop>
            <Line options={lineOptions} data={lineData} />
            <Calls>
              <div className="call">
                <div className="circle-1" /> Исходящие звонки
              </div>
              <div className="call">
                <div className="circle-2" /> Входящие звонки
              </div>
            </Calls>
          </Chart>
          <Chart>
            <ChartTop>
              <h1 style={{ fontSize: 18 }}>Исходящие звонки</h1>
              <DotsElement />
            </ChartTop>
            <Chips>
              <div className="chip">Отказ от подключения</div>
              <div className="chip">Ростов-на-Дону</div>
            </Chips>
            <Bar options={barOptions} data={barData} />
          </Chart>
        </ChartWrapper>
      </Container>
    </>
  );
}
