import Head from 'next/head';
import Image from 'next/image';
import axios from 'axios';
import { useState } from 'react';
import { useRouter } from 'next/router';
import { useDispatch, useSelector } from 'react-redux';
import {
  Button,
  InputWrapper,
  Form,
  LoginLayout,
  Gallery,
  DescriptionLogin,
  Remember,
} from '@/components/sharedstyles';
import Link from 'next/link';

export default function Login() {
  const [username, userNameSet] = useState('');
  const [password, passwordSet] = useState('');
  const [error, errorSet] = useState('');
  const [showPassword, showPasswordSet] = useState(false);
  const router = useRouter();
  const dispatch = useDispatch();

  const handleLogin = async () => {
    try {
      const credentials = { username, password };
      const response = await axios.post('/api/auth/login', credentials);

      if (response.status === 200) {
        const { token } = response.data;
        localStorage.setItem('token', JSON.stringify(token));
        dispatch({
          type: 'LOGIN',
          payload: token,
        });
        router.push('/dashboard');
      } else {
        throw new Error(response.data.message);
      }
    } catch (e) {
      errorSet('Введены неверные данные');
    }
  };

  return (
    <>
      <Head>
        <title>Вход в личный кабинет</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginLayout>
        <div className="split-1">
          <Form>
            <Link href="/">
              <Image
                src="/logo.svg"
                alt="logo"
                width={160}
                height={32}
                className="logo"
                priority
              />
            </Link>
            <h2 className="form-title">Вход</h2>
            <InputWrapper>
              <input
                type="text"
                value={username}
                name="user"
                className="input"
                onChange={(e) => userNameSet(e.target.value)}
                placeholder="user"
              />
            </InputWrapper>
            <InputWrapper icon={true}>
              <input
                type={showPassword ? 'text' : 'password'}
                value={password}
                name="password"
                onChange={(e) => passwordSet(e.target.value)}
                placeholder="password"
              />
              <span>
                <Image
                  src="/eye.svg"
                  alt="eye icon"
                  width={20}
                  height={20}
                  onClick={() => showPasswordSet(!showPassword)}
                  priority
                />
              </span>
            </InputWrapper>
            <div className="error">{error && error}</div>
            <Remember>
              <div>
                <input type="checkbox" />
                <div>Запомнить меня</div>
              </div>
              <Link href="/" className="link">
                Забыли пароль?
              </Link>
            </Remember>
            <Button onClick={handleLogin}>Войти</Button>
          </Form>
        </div>
        <div className="split-2">
          <Gallery>
            <div className="image-block">
              <Image
                src="/calls.png"
                alt="calls"
                fill={true}
                priority
                style={{
                  left: -135,
                  top: -110,
                  boxShadow: '0px 4px 32px #E8E7FF',
                  borderRadius: '8px',
                }}
              />
              <Image
                src="/dashboard.png"
                alt="dashboard"
                fill={true}
                priority
                style={{
                  left: 135,
                  top: 110,
                  boxShadow: '0px 4px 32px #E8E7FF',
                  borderRadius: '8px',
                }}
              />
            </div>
          </Gallery>
          <DescriptionLogin>
            <h1 className="title">Вся аналитика в одном кабинете</h1>
            <h4 className="description">
              Теперь просматривать аналитику и создавать отчёты
              <br />
              можно без нашей помощи
            </h4>
          </DescriptionLogin>
        </div>
      </LoginLayout>
    </>
  );
}
